# Server name, so far only used in the ttyrec metadata
server_id = "dbro"

# Script to initialize a user, e.g. make sure the paths
# and the rc file exist. This is not done by the server
# at the moment.
init_player_program = "/bin/init-webtiles.sh"

password_db = "%%CHROOT_LOGIN_DB%%"
# crypt() algorithm, e.g. "1" for MD5 or "6" for SHA-512; see crypt(3). If
# false, use traditional DES (but then only the first eight characters of the
# password are significant). If set to "broken", use traditional DES with
# the password itself as the salt; this is necessary for compatibility with
# dgamelaunch, but should be avoided if possible because it leaks the first
# two characters of the password's plaintext.
crypt_algorithm = "6"
# The length of the salt string to use. If crypt_algorithm is false, this
# setting is ignored and the salt is two characters.
crypt_salt_length = 16

nick_regex = "^[a-zA-Z0-9]{2,20}$"
max_passwd_length = 20

login_token_lifetime = 7

static_path = "%%CHROOT_WEBDIR%%/static"
template_path = "%%CHROOT_WEBDIR%%/templates/"
# Path for server-side unix sockets (to be used to communicate with crawl)
# By default, the system temp dir is used
# server_socket_path = ""

max_idle_time = 18000
connection_timeout = 600
kill_timeout = 10

max_connections = 100

recording_term_size = [80, 24]

# Watch socket dirs for games not started by the server
watch_socket_dirs = true

# Status file containing information about the currently running games
dgl_status_file =  "%%CHROOT_WEBDIR%%/run/status"
status_file_update_rate = 5

milestone_files = ["%%CHROOT_CRAWL_GAMEDIR%%/saves/milestones"]
list_savegames = false

# Set to a URL with %s where lowercased player name should go in order to
# hyperlink WebTiles spectator names to their player pages.
# Leave out to disable player page hyperlinks
player_url = "http://crawl.akrasiac.org/scoring/players/%s.html"

# Detach from session after startup?
daemon = true
pidfile = "%%CHROOT_WEBDIR%%/run/webtiles.pid"

uid = 1010
gid = 1011
umask = null
chroot = "%%DGL_CHROOT%%"

no_cache = false
game_data_no_cache = true
use_minified = false
use_cdn = true

# Non-SSL bindings
[[binds]]
port = 8081
address = "192.73.239.18"

# SSL
# [ssl_options]
# certfile = "./webserver/localhost.crt"
# keyfile = "./webserver/localhost.key"

# [[ssl_binds]]
# port = 8081
# address = "localhost"

[[games]]
id = "dcss-git"
name = "DCSS trunk"
version = "trunk"
mode = "Dungeon Crawl"
comment = "Start a standard game of Crawl."
crawl_binary =  "/bin/crawl-git-launcher.sh"
inprogress_path = "%%CHROOT_INPROGRESSDIR%%/crawl-git/"
rcfile_path =  "%%CHROOT_RCFILESDIR%%/crawl-git/"
socket_path = "%%CHROOT_WEBDIR%%/sockets"
morgue_path = "%%CHROOT_MORGUEDIR%%/%n/"
client_path = "%%CHROOT_WEBDIR%%/game_data"
macro_path = "%%CHROOT_RCFILESDIR%%/crawl-git/"
ttyrec_path = "%%CHROOT_TTYRECDIR%%/%n/"
send_json_options = true
morgue_url = "http://crawl.berotato.org/crawl/dev/morgue/%n/"

[[games]]
id = "dcss-farmer"
name = "DCSS farmer"
version = "farmer"
mode = "Dungeon Crawl"
comment = "Play a Farmer of Fedhas!."
crawl_binary =  "/bin/crawl-stable-launcher.sh"
inprogress_path = "%%CHROOT_INPROGRESSDIR%%/crawl-farmer/"
rcfile_path =  "%%CHROOT_RCFILESDIR%%/crawl-git/"
socket_path = "%%CHROOT_WEBDIR%%/sockets"
morgue_path = "%%CHROOT_MORGUEDIR%%/%n/"
client_path = "%%CHROOT_WEBDIR%%/game_data"
macro_path = "%%CHROOT_RCFILESDIR%%/crawl-git/"
ttyrec_path = "%%CHROOT_TTYRECDIR%%/%n/"
send_json_options = true
morgue_url = "http://crawl.berotato.org/crawl/dev/morgue/%n/"
pre_options = "farmer"

[game_link_settings]
hide_versions = []

[logging_config]
# filename = "webtiles.log"
format = "%(asctime)s %(levelname)s: %(message)s"
level = 20
